AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal serverless application with swagger definition for testing deployment

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ${DefinitionUri}
      StageName: ${stage}
      Variables:
        GetLambdaFunctionName: !Ref GetFunction
        stage: ${stage}

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.HelloHandler
      Runtime: java8
      CodeUri: ${CodeUri}
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello
            Method: ANY
            
Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value: !Sub https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${stage}
